[package]
name = "openantry-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Open Antry command-line client"
repository.workspace = true

[[bin]]
name = "openantry"
path = "src/main.rs"

[dependencies]
openantry-proto = { workspace = true }
openantry-core = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
clap = { workspace = true }
tokio = { workspace = true }
reqwest = { workspace = true }
dirs = { workspace = true }
